# Generated by Django 4.2.11 on 2024-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('senior', 'senior'), ('entry', 'entry')], max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
