# Generated by Django 4.2.11 on 2024-03-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.floor'),
        ),
    ]
