# Generated by Django 4.2.11 on 2024-03-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_details',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='staff',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.room'),
        ),
    ]
