# Generated by Django 4.2.11 on 2024-03-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_room_room_details_staff_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='room',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.room'),
        ),
    ]
